### ISSUE TITLE
[Feature Request to the Community]: You came here from Bartender? Reroute your money as well.

### ISSUE THREAD

**Issue by Schrank** [jordanbaird/Ice#100]
### Description

Become a sponsor -> https://github.com/sponsors/jordanbaird

Or throw some money via https://icemenubar.app

**Comment by Xytronix** [comment]
Really awesome of you to support an open source project. Would really love to turn this open source project into a major player

**Comment by jordanbaird** [comment]
Thank you for this!!

**Comment by TrveBlve** [comment]
Done and done.

**Comment by julienbordet** [comment]
Done !

**Comment by txkxgit** [comment]
Done! Thanks a lot for developing Ice!

**Comment by Spoekenkieker** [comment]
I purchased it on https://icemenubar.app 😊

**Comment by dylanmei** [comment]
What's up with Bartender?

**Comment by TrveBlve** [comment]
> What's up with Bartender?
> 
> Edit: Got it, mysteriously sold to Applause.

Sorry, just saw this. But yeah, you're right - there has been some weirdness with the sale of the app, which wasn't acknowledged until a thread on Reddit gained traction.

Either way, I'm happy supporting Ice since it does exactly what I need it to do.

**Comment by fishcharlie** [comment]
Purchased through Gumroad, and after realizing how great this app is, ended up sponsoring on GitHub. Thanks for your work on this @jordanbaird! Hope to see more improvements in the future.

**Comment by joaofrgomes** [comment]
> What's up with Bartender?
> 
> Edit: Got it, mysteriously sold to Applause.

Yep. After checking Applause's website and learning about their MO, it made me extra sad and also a bit mad at Ben Surtees himself (especially considering how I had bought a perpetual license fairly recently, in November); no matter how good of a developer he was, or how much he was paid, this is **not** the way to do things.

Also, because the buyers are obviously the worst offenders here (and, to Ben's credit and despite their horrid “sell us your app in five minutes and be done with it” messaging, he might've just been naïve and assumed they might show their faces, who knows…?), there should be an Applause-like “golden parachute app acquisition” service, but without the obsession on subscriptions as the **only** way of monetising apps and guaranteed transparency throughout the process.

Heck, it might even make apps seem **more** trustworthy post-acquisition, not less, which just goes to show how the guys at Applause know, deep down, they're villains in the grand scheme of things (if they weren't, they'd also be proud of acquiring apps and direct their marketing also at their future clients, but no; much like Google's clients are advertisers and users are the product, for Applause developers are the clients, the service is acquiring apps, the apps are a “product” which is rendered mediocre in the long run and end-users, while nominally “clients”, are just the suckers who finance the whole scheme, which has nothing to do with app development for the love of providing service). And guess what, even if they get rid of all the telemetry and keep the app running, I am **not** buying into that crap, I'd much rather donate to honest, open-source alternatives like Ice which won't be sold any day and can always be forked if the developer moves on.

And all of this reminds me of Serif's acquisition by Canva, and really put things into perspective now; despite being not very well received by users, and them publishing a pledge only after a great deal of backlash, at least they were fairly transparent and upfront about the transaction. And regarding its future, in hindsight and despite Canva's similar penchant for subscriptions, development on their apps did seem to have stagnated, which might've been due to a lack of funds. Judging from all the stupid and off-topic post-acquisition blog posts, we all know that Applause will basically keep Bartender on life support instead of polishing it or adding new features (maybe to compete with Apple's inevitable sherlocking of the entire category…?), which actually makes the behemoth that is Canva also look like benign challengers to Adobe at this point.

**Comment by fishcharlie** [comment]
@joaofrgomes Get over yourself. Ben Surtees doesn't owe you anything. You bought a license to his software. No where in that purchase did it include an agreement that he wouldn't sell the product to another developer/company. He's fully within his rights to do that. Sure it sucks. It's fine to be mad at the new owners for not being transparent and honest. But being mad at a developer who worked for years on an amazing product then deciding to move on is just crazy. It's his choice, you don't get to make his decisions for him.

Just be thankful that Ice exists and is open source. But a rage comment on an open source project about a closed source alternative doesn't improve the conversation here at all, and is incredibly off topic.

**Comment by joaofrgomes** [comment]
Let's put it this way: no, legally speaking, he doesn't owe me anything. But ethically? He owes me, and himself, basic respect.

Sure, there's nothing in that EULA promising that he would be the developer of Bartender until the end of time, and I'm pretty sure there could be some way of him to invalidate my perpetual license (I guess… selling the app to a different company is a way to test that?); but even if I had bought a regular, single-version one, or, heck, even if I had just downloaded the trial at the tail end of his tenure, don't you think I, along all other users, shouldn't be allowed to **know** who the actual developer was at all points, so I could make informed decisions regarding purchases and/or updates?

There's a reason why the MAS was created in the first place and, as someone aptly put it on Reddit or elsewhere (I can't recall), there's also a reason why signing certificates were created in the first place… Except not even those were enough to keep users truly informed throughout the transition; all we got was radio silence, then a bunch of weird blog posts, none of which addressed the sale, and then some really weird certificate and permissions shenanigans, and with an app that requests screen recording ones, at that! But, to wit, it was indeed the certificates that led the team at MacUpdater to figure out what had happened and both Applause and Ben (is it **really** Ben? His letter also seems AI-generated in places and it's posted on a supposedly personal domain that actually redirects to MacBartender's, it's not really hosted in a personal space, and at this point maybe an X/Twitter post would actually look more credible) to enter damage control mode and do… the only right thing you can do in these situations, which is to come clean. And it was too little, too late, I reckon. I don't trust either at this point, they're now more of a cautionary tale than anything else. 🤷‍♂️

Honestly: do you know of **any** user-facing business that didn't put out some sort of press release, even a basic boilerplate one, upon an acquisition? Do you think this is normal or acceptable in any way, shape, or form? In any industry? You see, in the business world, especially when dealing with end-users and individual customers, credibility is not just about money and EULAs, it's about transparency and trust, and in the absence of something like GitHub, where there are faces and names to any and all contributions, you'll just have to use your freaking blog or website like any other regular human being. To make subtle name changes to your certificate after the fact and try and hide/paper over your ineptitude is just the cherry on top. This was so ham-fisted of an acquisition that if I hadn't used his app before, I'd be convinced these people, including Ben, couldn't code or market their way out of a paper bag, it's still flabbergasting. And yes, if we are to give them the benefit of the doubt regarding Applause's legitimacy, this secrecy still reeks of shame all around, but if you can't handle shame, then… just don't enter mass business relationships with the public as an indie dev and work for a big company instead, easy.

And finally, please tell me how or why me airing some grievances while giving plenty of context in a thread dedicated to rerouting our money from Bartender to Ice (which, if you've seen elsewhere here, I intend on doing ASAP, and while I'm sadly too late to ask for a refund and literally reroute it instead of spending more still, I would if I could and I will spend more anyway), is off-topic or out of hand… Is mentioning Serif, another recently-bought company, also off-topic? Is mentioning the way Adobe just bought Macromedia and killed off FreeHand with nary a peep back in the day as… maybe a means give further context and praise FOSS in principle, off-topic, too? Go on, I'll wait.

**Comment by Xytronix** [comment]
I acknowledge thankfulness, transparency, and integrity. There is no reason to hate or mock Ben, it's rather about the decisions he made. I do not believe he didn’t know what he was doing. He did need money for a reason, the alternative of announcing a selloff to a company known for bad practice wouldn't make the situation incredibly better though. Announcing it prior to the sale would probably cut down acquisition pricing. Applause has many different reasons to not announce it as it cuts down revenue.

**Comment by joaofrgomes** [comment]
You are mostly right about him being entitled to make whatever decisions regarding his IP, but… I wholeheartedly disagree regarding such secret deals even being legal.

As a matter of fact, it seems to be so wrong, I suspect they run afoul of EU customer protection laws. Which is just ironic, considering how I had just come from dropping my ballot for EU Parliament elections.

In any case, this is a case of FAFO. These decisions come with consequences, and I can still have some smidge of empathy for the guy if he was really strapped for cash and needed an obscene amount thereof. Except we don't know if he was just being greedy. One would hope someone would bring the real grifters here, Applause, to task, and not even allow them to put such secret deals on the table. They're unethical and immoral, for reasons I hope I don't have to elaborate on further.

**Comment by tjharman** [comment]
I have donated $10 and uninstalled Bartender.
I see no point in bickering about Bartender, what's done is done, move on.

**Comment by core-code** [comment]
are there any plans of supporting Bartender's "API" that apps like ours have implemented so that the menubar item will only be displayed if there is something important to display?

it boils down to two things:
• setting the accessibility value of the menubar item to the numeric value of "important items". presumably the item is hidden of the accessibility value is empty or '0'
• sending global notifications to let menubar manager apps know when the value changes

here is how we've implemented that API:
```
            if (appsWithUpdatesCount)
                _visibilityManager.statusItem.button.accessibilityValue = @(appsWithUpdatesCount).stringValue;
            else
                _visibilityManager.statusItem.button.accessibilityValue = nil;
            [distributedNotificationCenter postNotificationName:@"Bartender.MenuBarItemStateUpdated" object:appBundleIdentifier userInfo:nil];
```

**Comment by jordanbaird** [comment]
@Schrank Thanks again for opening this. I think it's been open long enough, and a decent number of people have been purchasing or donating, so I'll go ahead and close this. I really do appreciate the support!
