### ISSUE TITLE
[Bug]: Unable to click or scroll on menu bar for full screen applications on secondary displays

### ISSUE THREAD

**Issue by zmkstn** [jordanbaird/Ice#115]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

For fullscreen applications in a secondary display, it is not possible to scroll or click to toggle the menu bar. There is no problem with doing any of this in the primary display.

In addition, clicking the menu bar to toggle the hidden section does not work for secondary screens, even on the desktop (non-fullscreen applications). However, if the hidden section was expanded prior, it is possible to click anywhere on the menu bar to untoggle the hidden section. Scroll is still functional, but only if (1) the secondary display is active and (2) it is in the desktop (non-full screen space).

### Steps to Reproduce

1. Fullscreen an application on a secondary display
2. Hover mouse to top of screen to show menu bar.
3. Click or scroll
4. Notice hidden section does not toggle

### Ice Version

0.9.0

### macOS Version

14.5

**Comment by zotanmew** [comment]
I'm having the same issue (can't click/scroll on the menu bar on secondary display) even without any fullscreen applications active on either display.

**Comment by bllchmbrs** [comment]
Same.

**Comment by joaofrgomes** [comment]
> I'm having the same issue (can't click/scroll on the menu bar on secondary display) even without any fullscreen applications active on either display.

Same here.

**Comment by dandreas** [comment]
![Screenshot 2024-06-09 at 2 00 33 AM](https://github.com/jordanbaird/Ice/assets/15883204/fc155fb3-68ed-4a6d-b9ca-e15be301b093)

I have the same issue, but it looks like the issue is that it is checking for clicks below the menu bar for me. It's a fairly small box, around the width of the tea kettle and bar chart icons on my menu bar, and similar in height.

**Comment by coryshaw1** [comment]
I've noticed this because macOS handles switching to secondary screens weirdly when it is not the active screen. The initial click when clicking on a secondary monitor's application that is not the current application seems to make that click in the taskbar of the monitor. Even if it's hidden and the app is fullscreen.

This happens constantly for me switching back and forth between macOS and my Parallels VM.

My current workaround is to just make sure that Show on Click, Show on Hover, and Show on Scroll are all disabled:
![image](https://github.com/jordanbaird/Ice/assets/5014172/321d50f4-6b40-40ca-a4ec-131da1a453e8)

Hopefully, this gives some ideas on how to debug this issue.

**Comment by zotanmew** [comment]
Sadly I'm still observing the same behavior on beta5, which includes the above commit. Clicking on the empty space on secondary displays doesn't show/hide icons.

**Comment by zotanmew** [comment]
@jordanbaird Yes, it does. It's a 14" MBP (2021)

**Comment by zotanmew** [comment]
Beta 6 seems to have solved the issue for me.
