### ISSUE TITLE
[Bug]: Dato.app "upcoming event" status item disappears

### ISSUE THREAD

**Issue by jbergstroem** [jordanbaird/Ice#119]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

<img src="https://sindresorhus.com/_astro/screenshot4.BQUiDBJi.jpg" width="50%">

[Dato](https://sindresorhus.com/dato) provides a calendar in the status bar. It also has a feature which shows the upcoming event (and is customizable). When using Ice, it disappears.

### Steps to Reproduce

1. Use Dato.app, enable upcoming events feature
2. Start Ice
3. Upcoming status bar item disappears

### Ice Version

0.9.0

### macOS Version

14.5

### Screenshots

Status bar without Ice running:

<img width="676" alt="Screenshot 2024-06-07 at 3 23 46 PM" src="https://github.com/jordanbaird/Ice/assets/176984/c244e4e5-f137-410a-a339-c0629042800d">

Status bar with Ice running:

<img width="558" alt="Screenshot 2024-06-07 at 3 23 30 PM" src="https://github.com/jordanbaird/Ice/assets/176984/83476e91-a480-4852-887c-039b693eff6d">

Status bar with Ice in edit mode running:

<img width="594" alt="Screenshot 2024-06-07 at 3 23 57 PM" src="https://github.com/jordanbaird/Ice/assets/176984/825b3411-4542-4aad-9638-e62af1fe00a6">

**Comment by gingerbeardman** [comment]
By default this item will be placed at the very left, in amongst the hidden items.

When it is visible you can cmd+drag to position it in the visible items

<img width="535" alt="image" src="https://github.com/jordanbaird/Ice/assets/49612/f162d6e1-2303-4742-b1b6-ef78154a242a">

But the next time one appears it will be in the hidden section again. I guess Ice considers them different menu items for some reason.

**Comment by jordanbaird** [comment]
It's not so much Ice, and more macOS that considers them different menu bar items. By default, every time a new menu bar item appears, its underlying "preferred" position is reset, which places it at the end of the menu bar (at the far left). Since the always-hidden section is also at the far left, that's where it appears. I'm working on a fix for this that involves Ice moving new items to a chosen location.

**Comment by gingerbeardman** [comment]
Thanks.

Another app this happes to is [xbar](https://xbarapp.com) but only if I choose "Refresh All" (which is when it recreates all icons). If the icons refresh themselves on their own schedule they do not move.

**Comment by gingerbeardman** [comment]
Thinking... maybe you could remember the positions of icons by their title and if they reappear in the hidden section automatically move them back to the visible section?

UIElementInspector.app says:
<img width="358" alt="Screen shot 2024-06-08 at 18 19 06" src="https://github.com/jordanbaird/Ice/assets/49612/7aff8bdf-8fd9-48e1-9cc4-68cb7ee152ae">

**Comment by jbergstroem** [comment]
> By default this item will be placed at the very left, in amongst the hidden items.

Yes, I noticed this the first time - so I reorganized it. After the first notification left its not available any longer, even in the leftmost section.

**Comment by gingerbeardman** [comment]
Oh, then my experience is different. Each item always pops up in the hidden section.

Ice only changes the spacing between items (largest spacing pushes items off screen so they are no longer visible) it doesn't actually remove any items. 

If you quite ice when you can't see the menu item, is the menu item visible again? And what about if you then restart Ice?

**Comment by jordanbaird** [comment]
As @gingerbeardman said, Ice can't remove items. If the item isn't in any section, or is still gone when Ice is quit, then the app (Dato in this case) isn't showing the item. I'm going to close this since it's not really a bug with Ice, but really comes down to the way macOS treats new menu bar items. Once, #6 and #26 are implemented, Ice will have full control over where individual items are placed.
