### ISSUE TITLE
[Bug]: Dock Ice App Icon Always Shows When Expanding Menu Bar

### ISSUE THREAD

**Issue by fishcharlie** [jordanbaird/Ice#128]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

Whenever you have Ice menu bar expanded the dock app icon shows up. When it's collapsed it disappears. It would be great if this could somehow be fixed so it's permanently hidden from the Dock.

### Steps to Reproduce

1. Expand Menu Bar
2. Observe that Ice dock icon shows
3. Collapse Menu Bar
4. Observe that Ice dock icon disappears

### Ice Version

0.10.0

### macOS Version

14.5 (23F79)

**Comment by jordanbaird** [comment]
This happens when you have the "Hide application menus when showing menu bar items" setting enabled in the "Advanced" settings pane. It is required to enable Ice to hide the application menus, as Ice must be active. Unfortunately, this is a macOS limitation, and there isn't much that can be done about it.
