### ISSUE TITLE
[Bug]: The Ice icon disappeared and cannot be brought up via the "Show Ice icon" option

### ISSUE THREAD

**Issue by x-ji** [jordanbaird/Ice#142]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

The Ice icon (the icon which you click on to show the hidden section) disappeared, and toggling the "Show Ice icon" option in the General tab under Settings and restarting Ice have not been helpful.

The Ice icon shows up when I try to rearrange menu bar items (by Cmd + dragging them) and can be dragged together with the other items. However, as soon as I quit the rearrangement mode, the icon disappears again.

### Steps to Reproduce

Not sure how this can be reproduced. I think it could be related to the fact that I first launched Ice with Bartender exited, but then while Ice was running, Bartender was accidentally launched for some reason. I quit Bartender immediately, but the Ice icon is gone. Uninstalling Bartender and logging out/in again doesn't seem to fix it either.

### Ice Version

0.9.0

### macOS Version

14.5

### Screenshots

The Ice icon is not shown normally:

<img width="217" alt="Screenshot 2024-06-11 at 14 38 53" src="https://github.com/jordanbaird/Ice/assets/2999209/de6a5b51-daf0-4c8e-8969-6f1fc9cc7e86">

When trying to rearrange icons, it shows up, but after rearrangement it's gone again:

<img width="220" alt="Screenshot 2024-06-11 at 14 39 01" src="https://github.com/jordanbaird/Ice/assets/2999209/9a5e552a-d92a-45b1-8001-f23d044b19e7">

**Comment by jordanbaird** [comment]
The icon in your screenshot isn't the Ice icon, but the separator item that starts the hidden section. The Ice icon, by default, looks like a dot. What likely happened is that Bartender rearranged Ice's icons so that the Ice icon is to the left of one of the separators (there are two, a larger one for the hidden section, and a smaller one for the always-hidden section). All icons should appear when you start dragging an icon, as you've noted. Find the Ice icon and drag it to the right of the larger arrow. An example of how this should be set up is in the README.

**Comment by x-ji** [comment]
You're right. The icon got rearranged somewhere to the left. I changed its shape to chevron so I probably confused it with a separator item. I changed it to the ice cube and found it when trying to rearrange the items again. Thanks for your prompt help!
