### ISSUE TITLE
[Bug]: Ice and Loop do NOT work together.

### ISSUE THREAD

**Issue by Fred-IV** [jordanbaird/Ice#166]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

Ice and Loop conflict. The menubar icon for loop will not show up.

### Steps to Reproduce

The description is clear.
Loop version is 1.0
https://github.com/MrKai77/Loop/releases/tag/1.0.0

### Ice Version

0.9.0

### macOS Version

14.4.1

### Screenshots

can't really screenshot this.
Loop icon is not visible.
These two apps do not like each-other.

**Comment by jordanbaird** [comment]
This is likely because macOS by default adds items to the far left of the menu bar, which is where Ice's always-hidden section is. Option+click the Ice icon (a dot by default) to show the section. If you still don't see it, Loop doesn't have an item in the menu bar and might need to be configured in its settings to have one. Ice doesn't (and can't) remove items. See #6 for more details.
