### ISSUE TITLE
Ice causing DRM media playback to flicker

### ISSUE THREAD

**Issue by danhew** [jordanbaird/Ice#22]
The screen recording feature in Ice seems to playing havoc when streaming DRM media. 

Apple TV and the Prime Video app both flicker when playing media, with the latter stating that the device doesn't meet content protection standards.

Playback of DRM media works immediately after quitting Ice

**Comment by jordanbaird** [comment]
Wow, that's bad. Looking at the logs, it looks like it's continuously trying and failing to capture the desktop background. It shouldn't even be trying unless menu bar appearance features are enabled, so that can be step 1 of the fix. Step 2 is a little more tricky. Screen capture is needed in order to place the desktop background over the top of the menu bar. But it obviously doesn't play nice with DRM streaming services, which I think is probably by design on Apple's part. So the question is, how do we detect when DRM video is being streamed so we can stop the screen capture?

**Comment by jordanbaird** [comment]
I believe I have found a fix. Once the next release comes out, let me know if the problem persists.
