### ISSUE TITLE
[Bug]: Even after the 0.10 update, icons don't appear in the "always shown" section after reboots.

### ISSUE THREAD

**Issue by efthymist** [jordanbaird/Ice#221]
### CHECK EXISTING AND FREQUENT ISSUES

- [X] I have searched existing issues, and this bug has not been reported

### Description

After the 0.10 update, I have completely disabled the "always hidden" section. I rearranged the icons the way I want them, and set certain icons to always show (e.g. Little Snitch and 1Password), along with some system icon such as Focus Profiles, Language, Battery, Spotlight,Control Center, Siri, Date.

After every reboot, 1Password still gets hidden.
![Untitled 2](https://github.com/jordanbaird/Ice/assets/56431063/92a13e3b-b214-49b8-a584-7a99bb929a5c)

### Steps to Reproduce

1. Disable the Always Hidden section.
2. Arrange the icons the way you want them.
3. Reboot.

### Ice Version

0.10.0

### macOS Version

14.5

### Screenshots

![Untitled 2](https://github.com/jordanbaird/Ice/assets/56431063/dcd73fab-c7e6-40e6-8aea-7e99214b1a0b)

**Comment by jordanbaird** [comment]
The 0.10.0 update does not contain a fix for this problem. It doesn't stop macOS from rearranging the items for certain apps (ones that don't store the positions of their items). macOS still places the items by default at the far left of the menu bar, which is now the hidden section because you've disabled the always-hidden section. The fix for this will come when #6 and #26 are implemented, which is currently set for 0.11.0. Closing, as this is already tracked.
