### ISSUE TITLE
[Bug]: clicking on icon in (floating) Ice Bar triggers app menu

### ISSUE THREAD

**Issue by e-kotov** [jordanbaird/Ice#236]
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

When using `Ice Bar` feature with apps that have a lot of menus, menu items of that active app are activated instead of icons that a user clicks in the floating `Ice Bar`

### Steps to Reproduce

1. Enable the floating `Ice Bar`.
2. Open an app that has a lot of menus that do not fit on the screen (I use https://qgis.org/ ) which leads to even the items that you set in `Ice` as always visible to be hidden (not sure if that is a prerequisite for other steps).
3. Click the `Ice` menu bar icon to reveal the `Ice Bar` OR just hover around the location where the menus end and menubar icons begin (if you have that enabled).
4. Try clicking on any of the icons of the apps that had their icons hidden by `Ice`.
5. A menu item of the currently active app will be activated (clicked) instead of the icon that you clicked (see the video attached)

### Ice Version

0.10.2

### macOS Version

14.5

### Screenshots

https://github.com/jordanbaird/Ice/assets/8681379/92e332e8-9789-4ef2-a74c-a1962cba7d57

**Comment by NewsGuyTor** [comment]
Yeah, this is a pretty critical bug. The Ice Bar is unusable for all apps that you want to be able to click ATM.

**Comment by okuramasafumi** [comment]
I also see this error with any app, even when the app doesn't have many menu items such as Finder.

**Comment by jordanbaird** [comment]
@okuramasafumi That's weird...I wouldn't think that should be the case. The only reason this is happening is because it's trying to click the shown item, but the position of the item is behind the application menus.

**Comment by okuramasafumi** [comment]
https://github.com/user-attachments/assets/d6828310-1264-45cb-b3a6-8558e85f3d94

This is what I do.

**Comment by ksc98** [comment]
Yup, I can't actually "use" (click on) any apps that have icons appearing in the popup menu bar

**Comment by okuramasafumi** [comment]
@jordanbaird Although I'm new to Swift, I'm a OSS programmer and I'm happy to help.

**Comment by smartygus** [comment]
I'm seeing something that appears to be related: worth noting upfront that I'm on a MacBook Pro display with a notch in the middle, which you can't see in the screen recording, but effectively causes icons to be hidden that are in the space that the notch occupies.

So: when I click on an icon in the Ice Bar, and there's sufficient space between the last icon and the notch to fit this clicked-on icon, it appears, and (as made visible by the click effect in the screen recording software) Ice Bar clicks it. This (at least for me), seems to work fine.

It becomes a problem when I click on something that is too large to fit in the remaining space between the last icon and the notch: clicking here effectively does nothing. I suspect because Ice Bar is trying to re-show the icon and then click it, but macOS is hiding it because it's protruding into the notch space. See screen recording:

https://github.com/user-attachments/assets/6e862d92-1a5a-4ea6-9181-50ae5004c65b

Unsure what the best solution would be here, possibly something along the lines of temporarily showing the clicked-upon item further to the right (so inside the normally "Visible" section), so that there's hopefully always enough space for it, and then after the menu is no-longer active, it removes it from the Visible section and hides it after the configured time out?
Unsure if this is technically possible though.

**Comment by jordanbaird** [comment]
@smartygus This is pretty much what I'm trying. I think I have something that will work for most cases, but I haven't thoroughly tested it yet.

**Comment by jordanbaird** [comment]
@okuramasafumi I'd appreciate any help. I just don't know how to help people get started. There's a lot more complexity than meets the eye to moving menu bar items.

**Comment by jordanbaird** [comment]
I've tested the fix for this about as much as one person can, and it works well for me. We can re-open this issue, or open a new one if there are still problems.

**Comment by okuramasafumi** [comment]
I updated Ice to `0.10.3` and still see this problem.

**Comment by e-kotov** [comment]
Things seem to be better now. See attached video.


https://github.com/user-attachments/assets/c3ed6255-ffb7-4269-a5ba-7bbd40a8af7c

**Comment by jordanbaird** [comment]
@okuramasafumi Your problem isn't related to this. This is specifically for app menus being triggered by shown items while your issue is that items just aren't being shown at all. This has been a known issue that I'm still trying to figure out a fix for. I noticed you have Magnet. Does the problem still happen if you quit it? There have been issues with that app in the past.

**Comment by okuramasafumi** [comment]
Oh I see. Yea I use Magnet bunch of other apps. I'll explore to quit some of them.

**Comment by jordanbaird** [comment]
@e-kotov Good to hear. Although I am seeing a bit of weirdness in the video, like the order of items being inconsistent. It also looks like your brightness adjustment icon wasn't hidden again afterwards, but that's a separate issue. These all feel like things that can be fixed with further implementation, though.

**Comment by jordanbaird** [comment]
@okuramasafumi Especially look for apps that monitor or alter mouse events, as those are what Ice uses to move items.

**Comment by okuramasafumi** [comment]
@jordanbaird Now I see why Ice doesn't behave as I expect.
When I click on icon on Ice Bar, Ice tries to move that item onto the "real" bar. If it's successful, it works. However, when the real bar is "full", meaning there's no space left, it doesn't work and nothing happens.
So my workaround is to always keep space on the real bar. However, the reason that I want to use Ice is that I don't want to think about menu bar too much, so it's sad...
And when I want to click 2 items on Ice bar, I need to wait for the first one to disappear from the real bar. So I guess it requires a fix anyway.

**Comment by jordanbaird** [comment]
@okuramasafumi Ah, I just realized, based on your screen recording you have a MacBook with a notch, yes? I didn't take that into account with this fix, but I believe it's different enough to warrant a separate issue.
