### ISSUE TITLE
[Feature Request]: Display the app icon upon activation by hotkey or other conditions.

### ISSUE THREAD

**Issue by llity** [jordanbaird/Ice#261]
### Check Existing Issues

- [X] I have searched existing issues, and this issue is not a duplicate

### Description

Display the software status icon when it is active, focused, or activated by a hotkey.

Thanks.

**Comment by jordanbaird** [comment]
By this, do you mean the Ice icon in the menu bar?

**Comment by llity** [comment]
I am referring to the capability of dynamically showing the menu bar item for each software application. When I activate or use the software, its menu bar item should automatically appear; when I'm not using it, it should automatically hide.

**Comment by jordanbaird** [comment]
Oh I see. Yes, this should be possible once triggers are implemented.

**Comment by llity** [comment]
Thanks.

**Comment by llity** [comment]
Perhaps we could establish customized groups here, activated by shortcuts, to showcase the collection of menu bar items.
![image](https://github.com/user-attachments/assets/f226ccf5-5353-4350-9415-377e9fb5d8c8)

**Comment by jordanbaird** [comment]
I'm going to close this, as there are multiple other feature requests that cover what has been discussed here. Showing icons with trigger conditions is covered by #62, and combining items into groups is covered by #46. Showing with hotkeys is on the roadmap, but I'll open an issue for it so that it's officially tracked.
