### ISSUE TITLE
apps are moved to always hidden section

### ISSUE THREAD

**Issue by rebdeg** [jordanbaird/Ice#29]
After every reboot I always find the same apps being moved to the always hidden section. I move them back and after a reboot they are once again in the always hidden section. The only app I do want in the hidden section is spotlight, but it moves 1password and dropbox automatically to always hidden. See screenshot.
[Schermafbeelding van Safari om 15 mrt 2024, 15_21_01.pdf](https://github.com/jordanbaird/Ice/files/14616778/Schermafbeelding.van.Safari.om.15.mrt.2024.15_21_01.pdf)

**Comment by jordanbaird** [comment]
This is because Ice doesn't currently have control over individual menu bar items. It just hides the entire section. macOS is likely doing something to reset the position of certain menu bar items on reboot, so they show up at the end of the menu bar, A.K.A. the always hidden section. I plan on fixing this with the upcoming menu bar profiles feature, which will save the location of each menu bar item (regardless of whether profiles are configured or not), and move the items to their previously saved positions when Ice launches.

**Comment by qns7** [comment]
That one is very annoying and the only app I came across which doesn't do that is (unfortunately) bartender, which as we know, costs ~20€/$ after the trial period. @jordanbaird It would be so awesome if you could fix that :) Have a nice day.

**Comment by bobbd2000** [comment]
+1 to being able to disable the always hidden section. And I too have 1Password and Dropbox always moved. Anyone know why it's those two? I usually have Dropbox hidden and 1Password visible.

**Comment by jordanbaird** [comment]
I'm working on getting this out for the next release. I'm just now realizing that this is already tracked in #6, so I'm going to close this in favor of that issue. I'll post updates there.
