### ISSUE TITLE
[Feature Request] Move menu bar away from screen edges

### ISSUE THREAD

**Issue by fastnlight0** [jordanbaird/Ice#32]
In bartender, you can move the menu bar away from the screen edges, which, in my opinion, looks really cool. Is it possible for this to be implemented in Ice? Currently, in split mode the bar is still connected to the screen edge, and I wanted to move it slightly away from the edge.

Screenshot from bartender:

<img width="296" alt="Screenshot 2024-03-19 at 3 09 47 PM" src="https://github.com/jordanbaird/Ice/assets/77035115/ed18299c-4b19-43f9-b76a-4511279c3e92">

**Comment by jordanbaird** [comment]
Is this on one of the newer MacBooks with the bigger menu bar? Because macOS doesn't give control over the exact position of the menu bar. Bartender is likely just insetting the size of the menu bar on the newer devices. Ice can definitely do the same, I just don't have access to a newer MacBook to test it on.

Could you post a screenshot of what it looks like on the same machine with Ice?

**Comment by fastnlight0** [comment]
I have a standard MacBook Pro without the notch and bigger menu bar. Here's what it looks like with Ice:

![Screenshot 2024-03-21 at 7 47 55 AM](https://github.com/jordanbaird/Ice/assets/77035115/0234a005-ca2a-4188-a96a-0fa9b08fb3d1)

The menu bar is directly attached to the edges of the screen.

**Comment by muuvmuuv** [comment]
This would be a cool feature for external display when using rounded menu bar since it is not directly at the edge.
