### ISSUE TITLE
[Bug]: Ice hates my Figma menu bar icon

### ISSUE THREAD

**Issue by stavrosquantox** [jordanbaird/Ice#325]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Out of all the apps that appear in my menu bar, my most used one doesn’t play well with Ice. I set my Figma icon to be always shown. Upon restarting Figma the first time, the icon didn’t show at all. I opened Ice and saw that it had moved the icon under Always hidden. Then upon the second restart of Figma the icon is nowhere to be found anymore, not listed under any of the three sections, like it doesn’t exist at all.

Also, just out of curiosity, how’s Ice’s performance/resource usage compared to Bartender? I’m a long time Bartender user and I decided to give Ice a chance. But for the last two days my laptop’s been running a bit hotter with the same workload and the only thing that changed was Bartender to Ice. And I don’t recall ever seeing Bartender as high as Ice on the CPU usage scale, and it’s on an M3 Max.

### Steps to Reproduce

1. Set Figma’s icon to always show;
2. Upon second restart of Figma the icon moved to always hidden on its own;
3. Third time opening Figma the icon is nowhere to be found anymore.

### Ice Version

0.10.5

### macOS Version

14.6.1

**Comment by jordanbaird** [comment]
The Figma item being moved to the always-hidden section is due to a macOS behavior. See #298 for more information, as well as what will be done about it.

I'm not sure why it disappeared after your second restart of Figma. Does restarting Ice make it show again?

As for CPU usage, if you're using Activity Monitor, it might be a little misleading at first as to what the true usage is. Ice monitors for the focused app and does quite a bit of work when it changes. So when you first open or activate Activity Monitor, then yes, the CPU usage will be pretty high for several seconds. Depending on the update frequency you have Activity Monitor set to, it could show higher usage for around 20 seconds after an app switch. But it should drop down to under 1% afterwards, which I believe is comparable to Bartender. I am of course, always working to improve performance, so the high usage will hopefully improve over time.

**Comment by stavrosquantox** [comment]
Thanks for the quick reply @jordanbaird, highly appreciate it!

And thanks for pointing me to where you address this issue. Just so you know, even though according to your comment is a macOS issue, I never had problems with this while using Bartender and I never used profiles. I just have a way of ordering my icons permanently to satisfy my OCDs and never change the order, neither use different arrangements via profiles. They have never moved from how I had them originally arranged.

Thank you for what you’re doing in any case!

**Comment by stavrosquantox** [comment]
And sorry, to answer tour question, the Figma icon returns after I restart Ice, and it also shows up under the always hidden if I manually drag to re-arrange the icons directly in the menu bar.

**Comment by jordanbaird** [comment]
@stavrosquantox With Bartender, as far as I understand, even if you don't use multiple profiles, it still uses a default profile behind the scenes to manage the order of items. Otherwise, it would have no way of remembering their positions. In the case of Figma, it will always be added to the far left without some sort of intervention. You can verify this by ensuring that both Ice and Bartender have been quit, then moving the Figma item somewhere else (say somewhere in the middle). Once you restart Figma, it will be back at the far left. You can then open Bartender and it will move it back to the position it remembers, which is exactly what Ice will do once profiles are implemented.

**Comment by jordanbaird** [comment]
I think the missing item is related to #283, so I'm going to close this issue to keep things streamlined.

**Comment by stavrosquantox** [comment]
@jordanbaird yep, that actually makes sense about Bartender using a profile by default.

And just so you know, I just tried opening other apps that also go to the far left, but all except Figma seem to be working just fine. And they even respect the order I've assigned to them. Only Figma seems to be crapping its pants constantly.
