### ISSUE TITLE
Double click for the "Always Hidden" section

### ISSUE THREAD

**Issue by gabrieles02** [jordanbaird/Ice#33]
Hi, 
I suppose it was a bug before, but a nice one for me. After the latest update, I can no longer double click the menu bar to see the always hidden items. I found it really useful since I keep most of my rarely used apps there, but I still want to have easy access to them. I wish there was an option in the setting to enable this "double tap to see Always Hidden items".

**Comment by jordanbaird** [comment]
I can go ahead and add it back as an option :)

In the meantime, you can Option+click the Ice icon to show the always hidden section, but I get the need for a quicker method

**Comment by jordanbaird** [comment]
After playing around with this some more, I'm finding that it's difficult to create a good user experience with this feature. The setting should only be enabled when the "Show on click" feature is also enabled. Where and when do we show the setting? How do we make it clear that it only works when "Show on click" is checked? How do we do it in a way that doesn't clutter up the interface? I'm thinking that since there's already a way to easily show the always hidden section, that this feature is probably a little redundant.

Also, in an upcoming update, the always hidden section can also be shown when Option+clicking an empty area of the menu bar, so there will soon be two ways to easily show the section.

I’m going to revert the change, but let me know if you can think of a good way to enable this feature that doesn’t clash with existing settings.

**Comment by gabrieles02** [comment]
I understand how messy it might be for users. I suppose that Option+Empty Menu Bar area click is the best of both worlds. As much as I'd like it to be as intuitive as I imagine it being, this implementation is most definitely the best of both worlds, so thank you. I started this thread because I simply disliked the idea of having to look for the Ice button to open the always hidden section. Being able to press anywhere on the menu bar solved this issue for me ;) I will play around with the keyboard shortcuts as well. Maybe they will be well suited for me, though I doubt it will integrate well into my workflow. Thank you nonetheless.
