### ISSUE TITLE
[Feature Request]: Menu Bar Shape Option on Second Monitor + height + transparency

### ISSUE THREAD

**Issue by thartrich** [jordanbaird/Ice#370]
### Check Existing Issues

- [X] I have checked existing issues, and this issue is not a duplicate

### Description

Hey Jordan,

Would love to see a a few features to your Ice app. Super cool what you are working on!!

1.) This is active on screens with a notch. Curious if you can create a second option to [Use inset shape on **2nd monitor/screens without** a notch as well]

2.) Is it possible to increase the height of the menubar on a **2nd monitor/screens without a notch** to match the height of MacBook Pro with a notch?

3.) Would love to see a transparent option for the color picker for the solid fill. I have a dynamic wallpaper that moves between light and dark and would love for that color to either dynamically change to match the wallpaper or to be 0% opacity to perfectly match the color of the wallpaper.

4.) When I drag a window close to the menubar or when it's flush to the top, the menu takes on a slight tint. Is that normal?

5.) When switching between macOS spaces, the menu flashes the original menubar for a moment before rendering.

Much appreciated,

Tyler

### Screenshots

<img width="756" alt="4 ) Slight tint" src="https://github.com/user-attachments/assets/5a60b40d-c221-43a9-a908-b63f0931f139">
<img width="755" alt="3 ) Solid Fill Dark" src="https://github.com/user-attachments/assets/187799b4-2c70-455e-84d7-098561206ef2">
<img width="756" alt="3 ) Solid Fill Light" src="https://github.com/user-attachments/assets/b7912313-420c-4729-9f85-f255b8cc00bc">

**Comment by jordanbaird** [comment]
Hi Tyler,

Thanks for reaching out! Unfortunately, most of this is not possible due to limitations in macOS.

To address your points:

1. Inset shapes can only happen on screens with a notch due to the extra height of the menu bar. We have enough space to effectively draw the desktop background over parts of the menu bar as a separate layer, giving the illusion that the menu bar is inset. This is also how Ice draws the split and rounded shapes, as well as the tint.
2. It is not possible to change the size or position of the menu bar.
3. Because we're not actually changing the color of the menu bar, but drawing a tint over it, a transparent option is not possible.
4. What you're seeing is the window shadow being clipped by the overlay Ice is adding. This is normal, and can't be avoided.
5. This one can be addressed, and there is an issue open for it (#58).
