### ISSUE TITLE
[Feature Request]: Swipe to see different menu bar areas

### ISSUE THREAD

**Issue by Xytronix** [jordanbaird/Ice#45]
### Description

The problem I get with a lot of apps is that I can't access the remaining apps which get added inside the always hidden part of the menu bar.

An option to access those via swiping (similar to bartender) could work out

**Comment by jordanbaird** [comment]
This feature already exists, and as far as I can tell, behaves exactly like Bartender. You can access the always-hidden section by option-clicking either the Ice icon or an empty menu bar space. I could also add the ability to option-swipe to show the always-hidden section, or I could make it so that swiping left while the hidden section is visible would show the always-hidden section. Would one of those work?

**Comment by Xytronix** [comment]
Option clicking works, sometimes it keeps appearing and disappearing when pressed. This is solved by repeatedly pressing.

Although the addition of swiping left while the hidden section is there

I have too many menu bar items. Showing the always hidden section isn't a problem, accessing overflowing items is.
Please see screenshot.
<img width="1710" alt="image" src="https://github.com/jordanbaird/Ice/assets/32957125/e3b44bbd-c4b4-4516-88fb-d4f510fc6d6f">

This could be solved by additional layouts which could be accessed with keybindings or swiping.
Or options to hide the hidden part.

**Comment by jordanbaird** [comment]
I think I see what you mean. Currently Ice is only able to hide sections, not reorder them (which would be required to do what you're saying). To enable this, as well as features like item groups and layout presets, I need to get individual item movement working, which is quite a complicated thing. While I'm not saying this won't happen, it probably won't be very soon.

**Comment by jordanbaird** [comment]
There have been multiple similar feature requests, so I've opened #240 to track them together.
