### ISSUE TITLE
[Feature Request] Search Menu Bar Items

### ISSUE THREAD

**Issue by y-u-s-u-f** [jordanbaird/Ice#5]
Coming from Bartender, one feature I really miss is searching the menu bar items. Basically, there is a spotlight type window that lets you search all the items. If you click enter on any one, It opens it up, and temporarily (for like a minute) keeps the item shown, and then after a minute it hides it again.

**Comment by prenagha** [comment]
Agree this is a big feature for my use case. I can't recognize what app goes with each icon any longer (perhaps because I use menu hiding bars ;-)), so when I want to find a menu app to click it is near impossible.
The other app feature where you use a hotkey, then get a popup search on the app names, return key activates it in the menu bar was fantastic. I used it all the time.

If you are taking sponsorship for specific features @jordanbaird let me know. I mean I sponsor anyway, but would do a bunch extra for this one.

**Comment by jordanbaird** [comment]
@prenagha I can definitely expidite this feature. The infrastructure to move the individual items is there after 0.10.0. As far as sponsorships go, I'll gladly accept whatever amount you feel the app is worth to you, but don't feel like you have to.

**Comment by jordanbaird** [comment]
@prenagha By the way, not sure if you saw this, but the [first 0.11.0 beta](https://github.com/jordanbaird/Ice/releases/tag/0.11.0-beta.1) has the search feature (although it is a little buggy). Unfortunately there isn't a way to update to the beta versions from within the app yet, so you'll have to do it manually from the release page.

**Comment by prenagha** [comment]
I did notice that and have been using it. Thanks again.
