### ISSUE TITLE
[Bug]: Newly started applications are not discovered

### ISSUE THREAD

**Issue by elementalTIMING** [jordanbaird/Ice#57]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

Hi,

I really love this tool, but one this is missing or buggy. Once the ICE is started and running and I start now a new application that creates a menubar icon - this new icon is not shown in the menubar. I need to quit ICE to make it visible.

Is there any fix or something I need to do to make this working properly?

### Steps to Reproduce

1. Start Ice on login
2. start a program (e.g. Mamp Pro, which creates a menubar icon)
3. not visible as long ICE is running

### Ice Version

0.8.0

### macOS Version

14.4.1

**Comment by jordanbaird** [comment]
This is a limitation of how Ice hides its icons, combined with how macOS inserts new icons into the menu bar. Since macOS inserts new icons at the end of the menu bar, they get placed into Ice's "always-hidden" section, meaning that you need to Option+click Ice's menu bar icon and drag the hidden icon into the section you want. I've been experimenting with ways around this, but it's more complicated than it seems.

**Comment by elementalTIMING** [comment]
> This is a limitation of how Ice hides its icons, combined with how macOS inserts new icons into the menu bar. Since macOS inserts new icons at the end of the menu bar, they get placed into Ice's "always-hidden" section, meaning that you need to Option+click Ice's menu bar icon and drag the hidden icon into the section you want. I've been experimenting with ways around this, but it's more complicated than it seems.

Thx for the feedback. That's very pity to hear, because "Ice" is so useful and small. I was wondering because Bartender is able to do it...
