### ISSUE TITLE
[Bug]: Menu bar appearance displaying incorrectly on external displays when main display has notch

### ISSUE THREAD

**Issue by Curzey** [jordanbaird/Ice#97]
### Check existing issues

- [X] I have checked existing issues and believe that my issue is not a duplicate

### Description

Visual bug where some of the **split bars** are transparent and window elements goes under it. 

### Steps to Reproduce

I'm not sure - will update if I figure it. 

### Ice Version

0.8.0

### macOS Version

14.4.1 (23E224)

### Screenshots

![Screenshot 2024-06-06 at 09 54 48](https://github.com/jordanbaird/Ice/assets/23375565/1ae83a80-aaf9-478c-99af-87af8bb15fa4)
![Screenshot 2024-06-06 at 09 54 27](https://github.com/jordanbaird/Ice/assets/23375565/0738e52f-22b2-45e7-a15f-2fa3d23ac8f1)

https://www.loom.com/share/f8461e388e5540f5a15b59f7e9f4cc1e

**Comment by Curzey** [comment]
I just notice now, that it only happens on my external screen. I didnt (dis)connect the screen when it happend.

**Comment by jordanbaird** [comment]
Does your main screen have a notch? It looks like it's trying to render with the size of a notched menu bar on the external screen.

**Comment by Curzey** [comment]
Ah yes - makes sense. Main screen has notch, external obviously does not. 

Let me know if I can help test anything.

**Comment by jaimefordham** [comment]
Apologies @jordanbaird I wasn’t sure this was the exact symptom I was getting in #102 

Happy to test anything if needed!

**Comment by jordanbaird** [comment]
@jaimefordham No worries! And thank you. I'll post an update in this thread when I have a fix. At that point, I'll probably have a beta build ready for you to test.

**Comment by kristof-rhaegal** [comment]
hi @jordanbaird , it seems to happen on the "secondary" display, not on the main.
I have a macbookpro with a notch, and it happens on that screen, not on the external display I set as "main". and when I plug a second external display, it happens on that one too. Never on the display identified as main.
![2024-06-07_09-02-52](https://github.com/jordanbaird/Ice/assets/45482231/0e525663-5212-4546-abf1-b69e6e124d68)

**Comment by langjacob518** [comment]
I'm having this same issue. External display kind of "strikes through" the top of the windows. I've gotten it to happen on my notched display as well but that is less consistent. Btw Jordan, Ice>>>>Bartender. Thanks for your skills.

**Comment by mbklein** [comment]
I came here to report something similar (but not identical) regarding the _Shadow_ setting. The location of the bottom edge of the shadow seems to depend on the size of the menu bar on the main display only.

I have a 14" MacBook Pro with a Built-In Display resolution of 1512x982 and a Thunderbolt Display with a resolution of 2560x1440.

### Thunderbolt Display set as main, Built-In Display set as extended

#### Thunderbolt Display menu bar
![shadow-thunderbolt-thunderbolt](https://github.com/jordanbaird/Ice/assets/196872/7841b7bf-a318-45f6-9f0c-c0891cf8d627)

#### Built-In Display menu bar
![shadow-thunderbolt-laptop](https://github.com/jordanbaird/Ice/assets/196872/c8105ac1-de41-4274-8e2b-729f0c0c288d)

### Built-In Display set as main, Thunderbolt Display set as extended

#### Thunderbolt Display menu bar
![shadow-laptop-thunderbolt](https://github.com/jordanbaird/Ice/assets/196872/0b708848-0811-446e-a994-94c95e42f8f3)

#### Built-In Display menu bar
![shadow-laptop-laptop](https://github.com/jordanbaird/Ice/assets/196872/dd90af99-1814-4e66-b18f-2fa13b3eab8d)

If this should be a separate issue, please let me know. But since this issue seems to be about menu bar geometry and multiple screens, it seemed to fit.

**Comment by michaelrowe01** [comment]
I am seeing the same issue as @mbklein with version 0.9.0 .. Is there a setting I need to change? I have turned off any changes to menu bar appearance. 
<img width="847" alt="Screenshot 2024-06-21 at 08 45 48" src="https://github.com/jordanbaird/Ice/assets/14998936/61b31f23-e75b-4e56-9990-4bd3a6831590">

**Comment by jordanbaird** [comment]
@michaelrowe01 You need to change the tint from gradient to none. Alternatively, click "Reset" to be sure the settings are at their defaults.

**Comment by jaimefordham** [comment]
Any change there'll be a new release soon that bundles all these fixes?

**Comment by jordanbaird** [comment]
@jaimefordham Relatively soon. It's a pretty major release, with some features that need a bit more work. I don't want to over promise, but hopefully within the next few days to a week.
